Notas = []
Nota = float(input("Digite a nota do primeiro aluno"))
print(Nota)
Nota = float(input("Digite a nota do segundo aluno aluno"))
print(Nota)
Nota = float(input("Digite a nota do terceiro aluno"))
print(Nota)
Nota = float(input("Digite a nota do quarto aluno"))
print(Nota)
Nota = float(input("Digite a nota do quinto aluno"))
print(Nota)
Notas.append(10)
Notas.append(7)
Notas.append(4)
Notas.append(9)
Notas.append(5)

print(Notas)
maior_nota = max(Notas)
print(maior_nota)
menor_nota = min(Notas)
print(menor_nota)

media = sum(Notas) / len(Notas)
print(media)
